netlify.toml
package-lock.json
package.json

This project is now using [environment variables plugin](https://www.npmjs.com/package/netlify-plugin-contextual-env/v/0.3.0) via Netlify's in-app [plugins directory](https://app.netlify.com/plugins) and no need to install the npm package for that plugin
- Remove netlify plugin package
Title: Remove netlify plugin
Participants: @bangunbagustapa @yoslie @adzharamrullah @Ibwedagama @naufalihsank @maulanayuseph @maruf12

chore: remove netlify plugin

---

src/components/Agenda/AgendaPreview.vue

- [S28A3 - Pop up Preview Agenda
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recEbd0mTSlsCe6hF?blocks=hide)
- add tags on agenda preview
title: feat display tags on agenda preview
participants: @Ibwedagama @maulanayuseph @yoslie @bangunbagustapa

feat: display tags on agenda preview

---

src/components/Agenda/AgendaForm.vue

Title: Disable preview button
Participants: @bangunbagustapa @adzharamrullah @Ibwedagama @yoslie

chore(agenda form): disable preview button

---

src/components/NewsInformation/News/NewsMonthFilter.vue
src/components/NewsInformation/News/index.vue

- fix `start_date` and `last_date` params format on `News/Index.vue`
- fix `firstDate` and `lastDate` value format on `NewsMonthFilter` component
title: fix news date param format
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @yoslie

fix: fix news date param format

---

src/pages/News/CreateEditNews.vue

- [T95 - Preview - Prefix Berita - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recNoI1RH8mPTXYdf?blocks=hide)
- add method to inject news prefix
- mutate content data on submit and save
title: feat inject news prefix on submit
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @doohanas

feat: inject news prefix on submit and save news

---

src/components/NewsInformation/News/NewsTableAction.vue
src/components/NewsInformation/News/index.vue
src/repositories/newsRepository.js

- [S29A7 - Delete Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recWJb5vHMv7c2zr7?blocks=hide)
- add `deleteNews` method on `newsRepository`
- add delete functionality on `News` page
https://user-images.githubusercontent.com/33661143/156302919-b7fec747-b275-4d88-b077-bb57923485cd.mov
- the delete functionality is still not working right now because the `DELETE` API route is still in development
- it will be fixed asap
title: feat delete news
participants: @Ibwedagama @maulanayuseph @maruf12 @yoslie

feat: delete news

---

src/components/NewsInformation/News/index.vue

Before
After
title: change order of news status tab
participants: @Ibwedagama @bangunbagustapa @doohanas

refactor: change order of news status tab

---

src/components/NewsInformation/News/NewsPreview.vue

- [T96 - Skeleton Loader - Berita (CMS dan Web Publik) - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recZBedeWjb8aQfSc?blocks=hide)
- improve styling on news content (header, blockquote, image caption)
- add skeleton loader to news header and content
- **Skeleton Loader**
- **News Content**
title: improve news preview
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @doohanas

improve: news preview

---

src/pages/News/CreateEditNews.vue

- [T95 - Preview - Prefix Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recNoI1RH8mPTXYdf?blocks=hide)
Title: 
Participants: @bangunbagustapa @Ibwedagama @doohanas

fix(news): show prefix when previewing news

---

src/pages/News/CreateEditNews.vue

Change all `<div>` in editor content to be `<p>`.
Title: chore(news): replace div tag to paragraph tag
Participants: @bangunbagustapa @adzharamrullah @Ibwedagama @doohanas

chore(news): replace div tag to paragraph tag

---

src/common/components/Sidebar.vue

- [T70 - Inconsistency sidebar menu - Agenda - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recpt9Y7cukloj9A4?blocks=hide)
- add exact attribute on home route  ('/') `<router-link>`
- change `isExactActive` property to `isActive` so the nested route also become active link
title: fix active link styling on nested route
participants: @Ibwedagama @maruf12 @bangunbagustapa @naufalihsank @doohanas

style: fix active link styling on nested route

---

src/components/NewsInformation/News/index.vue

- fix news status counter not updating the data after users do some actions like publish, delete or archive the news
- fetch news status counter after updating news data
https://user-images.githubusercontent.com/33661143/159859778-0e1e3ada-b5c9-41c6-9121-083e7a10719c.mov
title: fix status counter not updating data
participants: @Ibwedagama @maulanayuseph @maruf12 @bangunbagustapa @naufalihsank @doohanas

fix: status counter not updating data

---

src/pages/Errors/InvalidRegistrationLink.vue
src/router/routes.js

- show an error page when the user clicks an invalid invitation link
- add `/daftar/error` route
- create `InvalidRegistrationLink` component
- redirect user to `/daftar/error` route if registration token is invalid
title: feat invalid link page
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank

feat: invalid link page

---

src/components/Settings/Member/ChangeEmailModal.vue
src/components/Settings/Member/DeactivateMemberModal.vue
src/components/Settings/Member/SetAdminModal.vue

Add a password eye icon to toggle the password visibility for `<ChangeEmailModal />`, `<DeactiveMemberModal />` and `<SetAdminModal />`.
https://user-images.githubusercontent.com/55199533/161470323-c269dd64-74e5-4c9c-9d07-2a39a24e2747.mov
Title: refactor: password input visibility
Participants: @bangunbagustapa @Ibwedagama @yoslie @maulanayuseph @naufalihsank

refactor: password input visibility

---

src/common/components/Restricted.vue
src/mocks/handlers.js
src/repositories/authRepository.js
src/store/modules/auth.js

- [S41A3 - Kontributor](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recifJxpXxqujZywU?blocks=hide)
- [S41A2 - Administrator](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recnggRF6R157aPXc?blocks=hide)
- [S41A1 - Group Admin](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recf5r1jTKYaBFJej?blocks=hide)
- add `permissions` state on `store/auth`
- get permissions data after login
- add `Restricted` component
- improve mock response for `/users/me` and `/auth/permissions`
title: feat permission

feat: permissions

---

package-lock.json
package.json
src/common/components/Restricted.vue
src/main.js
src/store/modules/auth.js

improvement from https://github.com/jabardigitalservice/portal-jabar-cms/pull/165
the previous PR introduce a bug that makes users cannot log in to the app.
- [S41A3 - Kontributor](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recifJxpXxqujZywU?blocks=hide)
- [S41A2 - Administrator](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recnggRF6R157aPXc?blocks=hide)
- [S41A1 - Group Admin](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recf5r1jTKYaBFJej?blocks=hide)
- add `jwt-decode` package
- get user permissions before rendering the dashboard
- get user permissions from `access_token`
- create `Restricted` component
title: feat user permissions
participants: @Ibwedagama @maulanayuseph …

feat: user permissions

---

src/App.vue
src/components/Settings/Member/ListSection/index.vue

- [S35A2 - View Detail Akun Anggota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/reciLujaYRdamR4Ln?blocks=hide)
Actual Result:
Jika klik tombol kembali, saat ini masih menampilkan halaman akun
Steps to reproduce:
- akses view list akun anggota
- klik aksi pada salah satu anggota
- klik lihat detail
- menampilkan halaman detail anggota
- klik tombol kembali
Expected Result:
Jika tombol kembali di klik maka akan kembali ke halaman view list akun anggota
- add `keep-alive` component to cache `router-view` but only for `Settings` page
- change `mounted()` hook to `activated()` hook to ensure data fetching is always run every time the user loads the settings page
https://user-images.githubusercontent.com/33661143/161892634-9ccd55df-8630-41fd-845b-c2d2b235503a.mov …

fix: state cache on settings page

---

src/components/CreateAccount/Form/index.vue

- refactor `CreateAccountForm` component
- adjust styling on smaller screen
_tested on 800 x 600 screen resolution_
**Before**
**After**
title: fix create-account-form styling on small screen
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @yoslie

fix: create-account-form on small screen

---

src/components/NewsInformation/News/NewsPreview.vue

`html2canvas` throws a CORS error when it tries to render an image from an external source (AWS S3 Bucket or Cloudfront). This happened because `html2canvas` tried to render images that has been cached by the browser. To fix this issue we can simply add a random query string to all the images to prevent the browser from caching them.
ref: https://stackoverflow.com/questions/42263223/how-do-i-handle-cors-with-html2canvas-and-aws-s3-images
- add a random query string on `headerImage` computed property
- add a random query string on all images when the user downloads the PDF
title: improve news preview download
participants: @Ibwedagama @bangunbagustapa @khihadysucahyo @naufalihsank

improve: news preview download

---

src/pages/News/CreateEditNews.vue

title: fix news prefix not change when user updates the location

fix: news prefix not change when user updates the location

---

src/store/modules/public-service/masterDataForm.js

- [T306 [PROD] - [Create Master Data Layanan] Gagal create layanan](https://app.clickup.com/t/860qyfeg6)
Failed to save the form as a draft because `technical` value is null or empty causing `application` object to be undefined
title: hotfix error save as draft when technical value is empty
participants: @Ibwedagama @doohanas

hotfix: error save as draft when technical value is empty

---

src/pages/LandingPage/CreateEditAccessLink.vue

- fix disabled enabled save form data not work on change logo in edit form quick link
- disabled button save logo in popup list when no logo selected
title: fix disabled enabled save button not work on change logo in edit form quick link
participants: @yoslie @naufalihsank @marsellavaleria19 @doohanas

update: fix change logo to trigger save button in edit form quick link
