src/components/ui/Header.vue, src/components/ui/Sidebar.vue, src/router/routes.js
- remove `tag` props on `router-link`
- add more routes with dummy page (will be changed later)
- adjust link styling
title: fix router link
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @naufalihsank
=> fix: router link

src/components/ui/Header.vue
- as described by the title 
**before**
**after**
title: improve header menu structure and styling
participants: @Ibwedagama @maulanayuseph @maruf12 @bangunbagustapa @naufalihsank @yoslie
=> chore: improve header menu structure and styling

src/mocks/handlers.js
- Add login handlers
Title: add login handlers
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @adzharamrullah
=> mock: add login handlers

src/components/Home/index.vue, src/components/ui/Maintenance.vue
- as the title describes
- create `Maintenance` component
- add `Maintenance` component to `Home` page
title: add maintenance page
participants: @Ibwedagama @maulanayuseph @adzharamrullah @yoslie @naufalihsank @bangunbagustapa
=> chore (maintenance): add maintenance page

src/components/Agenda/index.vue, src/pages/AgendaPage.vue, src/router/routes.js
- [S27A1 - View List Agenda
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recTTgwhlTGM1QRPw?blocks=hide)
- add `AgendaPage` on router
- create `Agenda` component
title: agenda page layout
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @naufalihsank
=> chore: Agenda Page Layout

package-lock.json, package.json, src/assets/styles/tailwind.css, src/components/Agenda/AgendaTable.vue, src/components/Agenda/index.vue, src/lib/date-fns.js, src/repositories/RepositoryFactory.js, src/repositories/agendaRepository.js
- [S27A1 - View List Agenda
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recTTgwhlTGM1QRPw?blocks=hide)
- add `date-fns` package
- add date formatting lib/helper
- fetch agenda data from API
- show data to table
- remove scroll bar on `<body>` tag to prevent visual bug
title: feat agenda list view
participants: @Ibwedagama @adzharamrullah @bangunbagustapa @yoslie @naufalihsank
=> feat: Agenda List View

src/components/Login/LoginForm.vue
- Remove reset form action
- A bit of refactoring some variable and method
https://user-images.githubusercontent.com/55199533/148334278-766624fd-d4cd-4515-9cbc-b9175a36d2b1.mov
Title: Remove reset form action
Participants: @bangunbagustapa @maulanayuseph @naufalihsank @Ibwedagama @yoslie
=> chore: remove reset form action

src/components/Agenda/AgendaTable.vue, src/components/Agenda/index.vue
[S27A1 - View List Agenda
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recTTgwhlTGM1QRPw?blocks=hide)
- add pagination functionality
title: feat agenda list view pagination
participants: @Ibwedagama @maulanayuseph bangunbagustapa @naufalihsank @yoslie
=> feat: agenda list view pagination

src/components/Agenda/AgendaDetail.vue, src/components/Agenda/AgendaPreview.vue, src/static/data/index.js
`AgendaPreview` component should be able to format the props data by itself, so it can be used in multiple places. Other changes are:
- adjusting style on the delete button
- remove unused computed props on `AgendaDetail` component
- add a conditional check to render data based on agenda type (online/offline)
- add a status map to static data so it can be used on other files
title: refactor agenda detail and preview
participants: @Ibwedagama @adzharamrullah @bangunbagustapa @naufalihsank @yoslie
=> refactor: agenda detail and preview

src/components/Agenda/CreateAgenda.vue, src/repositories/agendaRepository.js
- Add preview functionality
- Add create agenda functionality
https://user-images.githubusercontent.com/55199533/149449964-c226f5c7-86cc-4015-83f4-de71c7e2b7dc.mov
Title: Create agenda
Participants: @bangunbagustapa  @adzharamrullah @maruf12 @maulanayuseph @Ibwedagama
=> feat: create agenda

src/components/Agenda/AgendaTable.vue, src/components/Agenda/AgendaTableAction.vue, src/components/Agenda/index.vue
- [S28A3 - Pop up Preview Agenda
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recEbd0mTSlsCe6hF?blocks=hide)
- add `AgendaPreview` component on Agenda Page
- show agenda preview when user clicks `Pratinjau` action on table
- refactor some methods
https://user-images.githubusercontent.com/33661143/149465356-a98aa55c-adce-4d78-91ca-c67b0affe7ee.mov
title: feat agenda list preview
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie
=> feat: agenda list preview

src/components/Agenda/CreateAgenda.vue, src/lib/date-fns.js
- Add validation for date
- Add validation for time range
- Sync the checkbox input with selected date
- Sync the submit button with validation
https://user-images.githubusercontent.com/55199533/149701228-76b3eaa7-e6f2-4bf7-a3e6-2c3ec15fbeca.mov
Title: Create agenda validation
Participants: @bangunbagustapa
=> chore: create agenda validation

src/components/Agenda/AgendaDetail.vue, src/components/Agenda/AgendaTable.vue, src/components/Agenda/AgendaTableAction.vue, src/components/Agenda/index.vue, src/components/ui/BaseButton.vue, src/repositories/agendaRepository.js
- [S27A4 - Delete Agenda
](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec36LPq5yI3IST0o?blocks=hide)
- add disabled style on `BaseButton` component
- add delete prompt modal on `Agenda` and `AgendaDetail` component
- add delete agenda functionality
- there is no notification toast yet
on `Agenda` page
https://user-images.githubusercontent.com/33661143/149716496-6d106a32-f542-45cd-9ff8-71bfc2650808.mov
on `AgendaDetail` page
https://user-images.githubusercontent.com/33661143/149716510-961e0422-5a7a-44b3-ae96-d1ce0495a22b.mov
title: feat delete agenda
participants: @Ibwedagama @maulanayuseph @yoslie @bangunbagustapa
=> feat: delete agenda

src/components/Agenda/AgendaDetail.vue, src/components/Agenda/CreateAgenda.vue, src/components/Agenda/index.vue, src/components/ui/BaseButton.vue, src/components/ui/HeaderMenu.vue
base button component should not dictate the color of the button (except on disabled state) so it will not conflict with color customizations. with this approach, the `variant` props are no longer needed.
- refactor `BaseButton` component
- adjust other component that use `BaseButton` component
title: refactor base button
participants: @Ibwedagama @maruf12 @adzharamrullah @bangunbagustapa @yoslie
=> refactor: base button

src/components/Agenda/AgendaDetail.vue
- change agenda detail information structure
- fix data binding on category and category type
- before
- after
title: refactor agenda information structure
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @naufalihsank @yoslie
=> refactor: agenda information structure

src/components/Agenda/index.vue
title: refactor format time on agenda table
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie
=> refactor: format time on agenda table

src/components/Agenda/AgendaForm.vue
Title: refactor(agenda form): change data structure
Participants: @bangunbagustapa @naufalihsank @yoslie @maulanayuseph @Ibwedagama
=> refactor(agenda form): change data structure

src/components/Agenda/AgendaDetail.vue, src/components/Agenda/AgendaForm.vue, src/components/Agenda/index.vue, src/components/Login/ForgotPassword.vue, src/components/ui/BaseButton.vue, src/components/ui/BaseModal.vue, src/components/ui/Header.vue, src/components/ui/HeaderMenu.vue
improve base button to handle disabled state and change `jds-button` to `BaseButton` component
title: improve base button
participants: @Ibwedagama @maulanayuseph @maruf12 @adzharamrullah @bangunbagustapa @yoslie
=> refactor: improve base button

src/components/Agenda/AgendaForm.vue, src/lib/date-fns.js
- Change default date format
- Replace method for checking the today date
Title: Fix(agenda form): default date format
Participants: @bangunbagustapa @maulanayuseph @maruf12 @adzharamrullah @Ibwedagama @yoslie
=> fix(agenda form): default date format

src/components/Agenda/AgendaTable.vue, src/components/Agenda/index.vue, src/static/data/index.js
change agenda table column from `Status` to `Tipe Kegiatan`
- change `AGENDA_TABLE_HEADER` constant on `static/data`
- add `type` property on `items` computed
- add styling to `Tipe Kegiatan` column on `AgendaTable` component
before
after
title : refactor agenda table
participants: @Ibwedagama @maulanayuseph @naufalihsank @bangunbagustapa
=> refactor: agenda table

package-lock.json, package.json, src/components/Agenda/AgendaForm.vue
- Add url validation
- Add debounce to the method
https://user-images.githubusercontent.com/55199533/150480315-12f948f8-7c7a-41fd-a1ac-323f490a6fdc.mov
Title: Url validation
Participants: @bangunbagustapa @maulanayuseph @adzharamrullah @Ibwedagama @naufalihsank @yoslie
=> chore: url validation

src/components/Agenda/AgendaDetail.vue, src/components/Agenda/index.vue, src/components/ui/Toast.vue, tailwind.config.js
improve toast alert position and close animation
- add `close-to-top` animation on `tailwind.config.js`
- adjust toast animation and position on `Toast.vue` component
- add a toast alert on fetch error and delete action
https://user-images.githubusercontent.com/33661143/150740200-09a544c4-a268-4893-afb3-2c661b778930.mov
title: improve toast alert
participants: @Ibwedagama @bangunbagustapa @yoslie @adzharamrullah
=> improve: toast alert

src/components/Agenda/AgendaForm.vue
- Add validation for time input
https://user-images.githubusercontent.com/55199533/150739774-d12f4c29-9dae-41f7-9d54-8cbbd823c4b3.mov
Title: Add time validation
Participants: @bangunbagustapa @maulanayuseph @Ibwedagama @yoslie
=> chore(agenda form): add time validation

src/components/Agenda/AgendaForm.vue
- Fix time validation
Title: Fix time validation
Participants: @bangunbagustapa @naufalihsank @maulanayuseph @adzharamrullah @yoslie @Ibwedagama @maruf12
=> fix(agenda form): fix time validation

src/components/Login/LoginForm.vue
Title: change error message
Participants: @bangunbagustapa @naufalihsank @maulanayuseph @adzharamrullah @Ibwedagama @yoslie @maruf12
=> chore(login form): change error message

package-lock.json, package.json, src/pages/News/CreateEditNews.vue
- Add image compression using [Compressor.js](https://www.npmjs.com/package/compressorjs)
- Add file validation
https://user-images.githubusercontent.com/55199533/152292290-39efd406-aef3-4156-83a6-a2eda10c9329.mov
Title: Add hero banner image compression and validation
Title: Portal Jabar
Participants: @bangunbagustapa @maulanayuseph @maruf12 @naufalihsank @yoslie
=> feat: add hero banner image compression and validation

src/pages/News/CreateEditNews.vue, src/repositories/RepositoryFactory.js, src/repositories/mediaRepository.js
- Add image handler
https://user-images.githubusercontent.com/55199533/152465470-9464f58f-73a0-4a8d-b855-9628dd47b2ec.mov
Title: Add image handler for text editor
Participants: @bangunbagustapa @adzharamrullah @Ibwedagama @maulanayuseph @yoslie @naufalihsank
=> feat: add image handler for text editor

src/common/constants/index.js, src/pages/News/CreateEditNews.vue
- Add news publish date validation
https://user-images.githubusercontent.com/55199533/152465767-f03d5dbd-da62-424f-b1eb-9b17f3a33a2e.mov
Title: News publish date validation
Participants: @bangunbagustapa @maruf12 @adzharamrullah @yoslie
=> feat: news publish date validation

.eslintrc.js, src/pages/News/CreateEditNews.vue
- Add form validation
Title: Add news form validation
Participants: @bangunbagustapa @yoslie @doohanas @naufalihsank @maulanayuseph @Ibwedagama @adzharamrullah
=> feat: add news form validation

src/common/constants/index.js, src/pages/News/CreateEditNews.vue, src/repositories/RepositoryFactory.js, src/repositories/tagRepository.js
- Add news category
- Add tag suggestions
https://user-images.githubusercontent.com/55199533/152920873-a4fd25f3-ac4b-4c40-a571-c22df1696961.mov
Title: add news category and tag suggestions
Participants: @bangunbagustapa @maulanayuseph @Ibwedagama
=> feat: add news category and tag suggestions

src/pages/Agenda/CreateEditAgenda.vue, src/pages/News/CreateEditNews.vue
https://user-images.githubusercontent.com/55199533/153106867-b9921a9e-e4a1-4a7e-b821-4a6bbf57c053.mov
Title: add confirmation modal before user leave
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph @maruf12
=> feat: add confirmation modal before user leave

src/pages/News/CreateEditNews.vue, src/repositories/RepositoryFactory.js, src/repositories/areaRepository.js
- Add author
- Add area repository
- Add location input
https://user-images.githubusercontent.com/55199533/153341139-94251b4d-3a2f-4910-9137-756150efa248.mov
Title: Add author and location input
Participants: @bangunbagustapa @adzharamrullah @Ibwedagama @yoslie @maulanayuseph
=> feat: add author and location input

src/components/NewsInformation/News/NewsTable.vue, src/components/NewsInformation/News/NewsTableAction.vue, src/components/NewsInformation/News/index.vue
- move status label formatting to `NewsTable` component, so `NewsTableAction` has access to raw news status data
- conditionally render action button based on news status
https://user-images.githubusercontent.com/33661143/153344627-28be8599-2ccd-45ef-840f-6f6e141891aa.mov
title: feat show news action based on status
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @naufalihsank
=> feat: show news action based on news status

src/pages/News/CreateEditNews.vue
- Fix button type submitting the form accidentally
- Fix area id value
- Change default value type for date
- Fix image blob data type
- Fix validation form
- Change variable name to camelcase
Title: fix: news form data structure
Participants: @bangunbagustapa @yoslie @naufalihsank @Ibwedagama
=> fix: news form data structure

src/pages/News/CreateEditNews.vue, src/repositories/newsRepository.js
- Add create news repository
- Add save news method
- Refactor the pop up message
https://user-images.githubusercontent.com/55199533/153806288-d94efa5c-d3cb-4937-bbbd-d9ca6f978137.mov
Title: Add save news method
Participants: @bangunbagustapa @adzharamrullah @Ibwedagama @naufalihsank
=> feat: save news

src/components/NewsInformation/News/NewsTable.vue, src/components/NewsInformation/News/NewsTableAction.vue, src/components/NewsInformation/News/index.vue, src/repositories/newsRepository.js
- [S29A5 - Arsipkan Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recpIm2ieV11fO81q?blocks=hide)
- [S29A3 - Terbitkan Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec7VLZi5lCaToHhM?blocks=hide)
- add `updateNewsStatus` method on `newsRepository.js`
- refactor `NewsTableAction` and `NewsTable` component
- add publish functionality
- add archive functionality
https://user-images.githubusercontent.com/33661143/153821191-8486969a-74fe-485c-8843-61fccab7e35c.mov
title: feat publish and archive news
participants: @Ibwedagama
=> feat: publish and archive news

src/pages/News/NewsPreview.vue
title: refactor action on refresh button
participants: @Ibwedagama
=> refactor: change action on refresh button

src/pages/Agenda/CreateEditAgenda.vue
- Fix pop up modal still open when form successfully submitted
Title: Fix pop up modal still open when form successfully submitted
Participants: @bangunbagustapa @Ibwedagama @doohanas @naufalihsank @yoslie @maulanayuseph
=> fix: fix pop up modal still open when form successfully submitted

src/pages/News/CreateEditNews.vue
- Refactor confirmation modal
- Refactor submit method
- Save the news before leave the page
https://user-images.githubusercontent.com/55199533/153980207-48f0a4cd-1d25-4e9b-b7cf-766bb97d8dcd.mov
Title: Save the news before leave the page
Participants: @bangunbagustapa @adzharamrullah @maruf12 @maulanayuseph @Ibwedagama
=> feat: save the news before leave the page

src/common/components/ProgressModal.vue, src/pages/News/CreateEditNews.vue
- Add news submission
- Add progress bar modal
https://user-images.githubusercontent.com/55199533/153993800-60e5f284-9402-42f7-95ab-91449100728a.mov
Title: feat: news submission
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph
=> feat: news submission

src/pages/News/CreateEditNews.vue
- Validation for empty input
- Image type validation
Title: fix: news form validation
Participants: @bangunbagustapa @Ibwedagama @doohanas @maulanayuseph @naufalihsank
=> fix: news form validation

src/components/Agenda/AgendaTable.vue, src/components/NewsInformation/News/NewsTable.vue
- adjust empty text message on `JdsDataTable` component
title: adjust empty text message on table
participants: @Ibwedagama @maulanayuseph @maruf12 @bangunbagustapa @naufalihsank @doohanas
=> chore: adjust empty text message on table

src/pages/News/CreateEditNews.vue
- Fix tags data format when submitting the form
- Fix loading stuck when error uploading image
Title: fix: tags data format
Participants: @bangunbagustapa @naufalihsank @Ibwedagama @yoslie
=> fix: save news

src/pages/Agenda/CreateEditAgenda.vue
- Make agenda tag optional
- Add tag suggestion
https://user-images.githubusercontent.com/55199533/153789610-d0000e1c-d865-4f6c-8212-3b6f04c63280.mov
Title: Add agenda tag suggestion and make tag optional
Participants: @bangunbagustapa @yoslie @maulanayuseph
=> chore: agenda tag

package-lock.json, package.json, src/pages/News/CreateEditNews.vue, src/pages/News/NewsPreview.vue, src/store/index.js, src/store/modules/news.js
- Add vue persist to persist the state accross different windows
- Add vuex module for news preview
- Add news preview feature
https://user-images.githubusercontent.com/55199533/154412893-9143a964-1c72-4966-84c3-c57124e3c46f.mov
Title: feat: news preview
=> feat: news preview

src/common/components/Header.vue
- map state from store to get user data
- replace dummy image with user photo
title: refactor replace dummy avatar with user photo
participants: @Ibwedagama @maulanayuseph @yoslie @bangunbagustapa
=> refactor: replace dummy avatar with user photo

src/common/constants/index.js, src/pages/News/CreateEditNews.vue
Send duration value to the backend when creating news
- Change the value for the infinite duration in static data
- Refactor the structure data
Title: chore(news): send duration value when creating news
Participants: @bangunbagustapa @adzharamrullah @Ibwedagama @maruf12 @yoslie
=> chore(news): send duration value when creating news

src/common/components/LinkButton.vue, tests/unit/components/common/BaseButton.spec.js, tests/unit/components/common/LinkButton.spec.js
- add unit test for `BaseButton` component
- add unit test from `LinkButton` component
title: test improve unit test
participants: @Ibwedagama @maruf12 @maulanayuseph @bangunbagustapa @naufalihsank
=> test: improve unit test

src/common/components/SearchBar.vue, src/pages/Agenda/index.vue
- [S27A6 - Search Agenda](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/reco67x02MzAEbMCG?blocks=hide)
- improve `SearchBar` component
- add search functionality on Agenda page
https://user-images.githubusercontent.com/33661143/156709847-c961a5a5-881c-479a-a52e-6be8cf06140c.mov
title: feat search agenda
participants: @Ibwedagama @khihadysucahyo @bangunbagustapa
=> feat: search agenda

package-lock.json, package.json, src/pages/News/CreateEditNews.vue, src/repositories/newsRepository.js
- compare old data with new data
- only show button if in draft mode
- add update news method
- show prompt if user leave the page when editing
- show updated news info only when the status is draft
Title: feat: edit news
Participants: @bangunbagustapa @adzharamrullah @yoslie @maulanayuseph @naufalihsank
=> feat: edit news

src/components/Settings/AccountSettings.vue, src/components/Settings/MemberSettings.vue, src/pages/Settings.vue, src/repositories/RepositoryFactory.js, src/repositories/userRepository.js, src/router/routes.js
- Add settings page
- Add personal information
https://user-images.githubusercontent.com/55199533/157175165-00760f08-a213-4bc7-a913-2c455f7aa882.mov
Title: feat: personal information
Participants: @bangunbagustapa @yoslie @maulanayuseph
=> feat: personal information

src/components/Settings/Account/PrivacyAndSecuritySection.vue
https://user-images.githubusercontent.com/55199533/157176945-2da70424-15d9-402b-8997-303af0bbb0ea.mov
Title: feat: add privacy and security section
Participants: @bangunbagustapa @maulanayuseph
=> feat: add privacy and security section

package-lock.json, package.json, src/common/components/SearchBar.vue, src/components/NewsInformation/News/NewsCategoryFilter.vue, src/components/NewsInformation/News/index.vue
- [S29A8 - Filter Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recSS3qi85kNs9SMn?blocks=hide)
- [S29A9 - Search Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recpTEI6247nBsA0r?blocks=hide)
- only component layout for now, functionality will be implemented in other PR
title: news search filter layout
participants: @Ibwedagama
=> chore: news search filter layout

src/components/Agenda/AgendaTable.vue, src/pages/Agenda/index.vue
- fix table layout on a small device
- remove page description 
- remove unused section
**Before**
**After**
https://user-images.githubusercontent.com/33661143/157365137-1925d8ee-ce2d-47cb-85f9-eccdcc49e258.mov
title: improve agenda list
participants: @Ibwedagama @maruf12 @bangunbagustapa @doohanas
=> improve: agenda list

src/components/NewsInformation/News/index.vue
- [S29A9 - Search Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recpTEI6247nBsA0r?blocks=hide)
- [S29A - Sort Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recq8gJdaPi8MHLRi?blocks=hide)
- add filter functionality
- add search functionality
- improve table layout on small screen
https://user-images.githubusercontent.com/33661143/157371981-3f1b913a-de5d-446d-b401-c933b53f6453.mov
https://user-images.githubusercontent.com/33661143/157372032-29c710ad-accc-461b-a48d-e417a2c6e9f2.mov
title: feat search filter news
participants: @Ibwedagama @bangunbagustapa @yoslie
=> feat: search filter news

src/pages/News/CreateEditNews.vue
Title: fix: change duration type
Participants: @bangunbagustapa @doohanas @Ibwedagama @yoslie
=> fix: change duration type

src/components/NewsInformation/News/NewsTable.vue, src/components/NewsInformation/News/index.vue
- [S29A - Sort Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recq8gJdaPi8MHLRi?blocks=hide)
- add sort functionality
- there is an error when sorting news by the author because for now it is not supported by the backend service
- this issue is currently being fixed on the backend service
https://user-images.githubusercontent.com/33661143/157385562-5c45c9e1-db37-4d95-bb8e-bcdee7a7e45c.mov
title: feat news sorting
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @yoslie
=> feat: news sorting

src/components/Agenda/AgendaFilter.vue, src/pages/Agenda/index.vue
- add today's date as the default date filter
- improve date validation
- reset filter to actual params when clear button clicked
reset filter to actual params
https://user-images.githubusercontent.com/33661143/157586374-53852160-ca50-494c-9d72-44fc133c52e8.mov
improve date validation
https://user-images.githubusercontent.com/33661143/157586790-a3bfe9a1-fea5-4d1b-9654-6f881e8c9ed0.mov
title: improve agenda filter
participants: @Ibwedagama @maulanayuseph @adzharamrullah @bangunbagustapa @yoslie
=> improve: agenda filter

src/components/Settings/Account/PrivacyAndSecuritySection.vue, src/components/Settings/Account/index.vue
https://user-images.githubusercontent.com/55199533/157586214-25792ac1-e8e6-4cfa-970f-c7bfbf46ea57.mov
Title: feat: password validation
Participants: @bangunbagustapa @Ibwedagama  @adzharamrullah @maulanayuseph
=> feat: password validation

src/components/Settings/Account/NotificationSection.vue, src/components/Settings/Account/index.vue
=> feat: add notification

src/pages/News/CreateEditNews.vue
Image is still uploaded even though it's been validated, the early return will make sure we don't reach the set image method.
Title: fix: image upload
=> fix: image upload

src/pages/Agenda/CreateEditAgenda.vue
Add progress modal on agenda form to display the progress and prevent the button from being clicked during the process
https://user-images.githubusercontent.com/55199533/157599973-023d0952-2dcd-483d-b6ba-80393bb3925f.mov
Title: chore: add progress modal on agenda form
=> chore: add progress modal on agenda form

src/components/Agenda/AgendaFilter.vue
- [S27A5 - Filter agenda](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recY6IDf9M0ytJwVa?blocks=hide)
- Fix bug filter count showing inaccurate value before submitting
- Fix bug showing error message after resetting filter
- Fix bug date picker not showing correct date after closing the modal
- Fix styling on error message
title: fix agenda filter date
participants: @Ibwedagama @maulanayuseph @bangunbagustapa
=> fix: agenda filter date

src/components/Settings/Account/PrivacyAndSecuritySection.vue, src/repositories/userRepository.js
add update password method
https://user-images.githubusercontent.com/55199533/157796885-d550ac94-2bb0-4f22-90f1-b52a38176395.mov
Title: feat: update password
Participants: @bangunbagustapa @maulanayuseph @Ibwedagama
=> feat: update password

src/components/Settings/Account/PersonalInformationSection.vue, src/components/Settings/Account/PrivacyAndSecuritySection.vue
- Add hover
- Change label font size
Title: style(account settings): add hover state; change label font size
Participants: @bangunbagustapa @doohanas @Ibwedagama @maulanayuseph
=> style(account settings): add hover state; change label font size

src/components/NewsInformation/News/index.vue
title: refactor news author name
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie @doohanas
=> refactor: change author column value from unit name to author name

src/components/Settings/Account/PersonalInformationSection.vue, src/repositories/authRepository.js, src/repositories/userRepository.js, src/store/modules/auth.js
Change api endpoint for getting authenticated user data from `auth/me` to `users/me`.
Title: chore: change user endpoint
Participants: @bangunbagustapa @doohanas @Ibwedagama @naufalihsank @yoslie
=> chore: change authenticated user data api endpoint

src/pages/News/CreateEditNews.vue
Add skeleton loader when TinyMCE is not yet rendered.
https://user-images.githubusercontent.com/55199533/158121144-ea9b329c-8ea0-4a6e-a765-78b06cf8393d.mov
Title: feat(news): editor skeleton
=> feat(news): editor skeleton

src/pages/News/index.vue
- **Before**
- **After**
title: feat add keep alive to cache component state
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie @doohanas
=> feat (news): add keep-alive to cache component state

src/components/Settings/Account/PrivacyAndSecuritySection.vue
Fix the last password updated
Title: fix: the last password updated
Participants: @bangunbagustapa @naufalihsank @doohanas @maulanayuseph @yoslie @Ibwedagama
=> fix: last password updated

src/pages/Agenda/AgendaDetail.vue
- [T67 - Detail Agenda - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec6zqN1QgneCIum9?blocks=hide)
- remove `Status` column
- remove unused code
- show unit/OPD name on `Kategori` column
title: improve agenda detail
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank
=> Improve: agenda detail

src/common/components/Header.vue
- [T83 - Log Out - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec82FUEgEJCu5jA2?blocks=hide)
- refactor open and close modal method
- close user dropdown when logout modal open
https://user-images.githubusercontent.com/33661143/158322153-15c3ceb0-2e70-4d5c-9b8b-661bb107a518.mov
title: feat close user dropdown when logout modal open
participants: @Ibwedagama @bangunbagustapa @naufalihsank @doohanas
=> feat: close user dropdown when logout modal open

src/common/components/Header.vue
- [T92 - Logout - Abnormal Test - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/reczegDlbhlrrItpf?blocks=hide)
- when using `window.location.replace()` the app requests a new page from the server, it causes a slow logout process when the user's internet connection is slow
- the solution is to use **vue-router** instead of `window.location.replace()` so that the routing process will be done instantly even when the user is offline
- change `window.location.replace()` to  Vue `$router.push()`
https://user-images.githubusercontent.com/33661143/158331624-54b6f992-81a3-49f6-b4be-859a674812ae.mov
title: refactor logout routing process
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @yoslie @doohanas
=> refactor (header): refactor logout routing process

src/components/Login/ForgotPassword.vue
Title: fix: fix reset password validation
Participants: @bangunbagustapa @Ibwedagama @yoslie
=> fix: fix reset password validation

src/components/Login/LoginForm.vue
- [T49 - Login - CMS](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/reczYMKK6F0mLkhK7?blocks=hide)
- Remove trim modifier
Title: fix(login): fix password validation
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph @naufalihsank @yoslie
=> fix(login): fix password validation

src/pages/News/CreateEditNews.vue
Change wording on confirmation modal
Title: fix(news): confirmation modal wording
Participants: @bangunbagustapa @naufalihsank @Ibwedagama
=> fix(news): confirmation modal wording

src/router/index.js
Fix flicker issue when rendering the page for an unauthenticated user
Title: fix(route): fix route guard conditional
Participants: @bangunbagustapa @Ibwedagama @naufalihsank
=> fix(route): fix route guard conditional

README.md
title: improve readme file
participants: @Ibwedagama @yoslie @maruf12 @doohanas
=> improve: readme file

src/pages/News/CreateEditNews.vue
Fix toolbar floating
Title: fix: editor toolbar
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @adzharamrullah @maulanayuseph
=> fix: editor toolbar

src/components/Settings/Account/RequestUpgradeRoleSection.vue, src/components/Settings/Account/index.vue
Title: chore: request upgrade role layout
=> chore: request upgrade role layout

src/common/helpers/validation.js, src/components/Settings/Member/InvitationSection/index.vue, src/components/Settings/Member/index.vue
- [S36A3 - Add Akun Angota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recIZXlBbrJaxc9ek?blocks=hide)
https://user-images.githubusercontent.com/55199533/159410474-61d545ca-5b12-41b5-87e4-6bfa40fae57a.mov
Title: chore: member invitation layout
=> chore: member invitation layout

src/components/Settings/Member/ChangeEmailModal.vue, src/components/Settings/Member/DeactivateMemberModal.vue, src/components/Settings/Member/SetAdminModal.vue, src/pages/Settings/MemberDetail.vue
- [S35A1 - View List Akun Anggota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recIp9I1srTke3d7B?blocks=hide)
- create `DeactivateMemberModal` component
- create `ChangeEmailModal` component
- create `SetAdminModal` component
- add those component on member detail page
https://user-images.githubusercontent.com/33661143/159400221-116f8f7b-c9e5-4e00-8552-ff484015f3ae.mov
title: create member detail action modal
=> chore: member detail action modal

src/components/Settings/Member/ListSection/MemberTableAction.vue
title: refactor link to member detail page
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @doohanas
=> refactor: change router-link to member-detail page

src/components/Login/ForgotPassword.vue, src/components/Login/LoginForm.vue
- Replace and use email validation method `isValidEmail` from the utils file
Title: refactor: use email validation method from the utils file
Participants: @bangunbagustapa @maruf12 @yoslie
=> refactor: use email validation method from the utils file

src/pages/CreateAccount.vue, src/repositories/RepositoryFactory.js, src/repositories/registrationRepository.js, src/router/routes.js
- [S36A1 - Create Account Kontributor/Administrator](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec9DgwFzFRxyNBjA?blocks=hide)
- add `/daftar` route
- add `CreateAccount` page component
- validate invitation token before rendering the page
title: feat validate registration token
participants: @Ibwedagama @adzharamrullah @bangunbagustapa @naufalihsank
=> feat: validate registration token

src/components/Settings/Member/InvitationSection/index.vue, src/repositories/RepositoryFactory.js, src/repositories/registrationRepository.js
- [S36A3 - Add Akun Angota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recIZXlBbrJaxc9ek?blocks=hide)
https://user-images.githubusercontent.com/55199533/159625804-00b2e940-c035-4043-8ccd-1f7d87e6223f.mov
Title: feat: create invitation
Participants: @bangunbagustapa @Ibwedagama @adzharamrullah @naufalihsank
=> feat: create invitation

src/repositories/RepositoryFactory.js
There's a conflict with importing the file that already imported
Title: fix: fix file already imported
Participants: @bangunbagustapa @naufalihsank @maulanayuseph @yoslie
=> fix: fix file already imported

src/layouts/AppLayout.vue, src/layouts/AppLayoutPrivate.vue, src/router/routes.js
When the user is not authenticated and visit the web, the layout renders the dashboard layout instead of login layout.
Could be improved in the future so we don't have to manually define the layout in meta object for every route.
Title: fix: app layout
Participants: @bangunbagustapa @naufalihsank @adzharamrullah @Ibwedagama @doohanas @maulanayuseph
=> fix: app layout

src/components/Settings/Member/ChangeEmailModal.vue, src/components/Settings/Member/DeactivateMemberModal.vue, src/components/Settings/Member/SetAdminModal.vue
- improve `DeactivateMemberModal`
- improve `ChangeEmailModal`
- improve `SetAdminModal`
title: refactor member action modal
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @yoslie
=> refactor: member action modal

src/common/components/BaseButton.vue, src/components/CreateAccount/Form/DetailInformationForm.vue, src/components/CreateAccount/Form/PasswordForm.vue, src/components/CreateAccount/Form/index.vue, src/pages/CreateAccount.vue
- [S36A1 - Create Account Kontributor](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec9DgwFzFRxyNBjA?blocks=hide)
https://user-images.githubusercontent.com/55199533/160049666-d6ddbc84-1fed-4c7c-8d7d-b91c141452b3.mov
Title: chore: create account
Participants: @bangunbagustapa @adzharamrullah @Ibwedagama @maulanayuseph
=> chore: create account

src/components/Settings/Account/RequestUpgradeRoleSection.vue, src/repositories/RepositoryFactory.js, src/repositories/templateRepository.js, src/repositories/userRepository.js
- [S37A6 - Request Upgrade Role](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec4ZGoBR8dpUFo5O?blocks=hide)
https://user-images.githubusercontent.com/55199533/160068394-f41df7e7-eb97-49d7-8e44-d5828d2f3e3f.mov
Title: feat: request upgrade role
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph
=> feat: request upgrade role

src/components/NewsInformation/News/NewsTable.vue
title: fix news table column width
participants: @Ibwedagama @bangunbagustapa @naufalihsank @doohanas
=> fix (news-table): fix updated date column width

src/common/components/Header.vue
Change static user role name and get the name from API
Title: fix: user role name
Participants: @bangunbagustapa @adzharamrullah @doohanas @Ibwedagama @naufalihsank @yoslie
=> fix: user role name

src/components/Settings/Member/ListSection/MemberTable.vue, src/components/Settings/Member/ListSection/MemberTableAction.vue, src/components/Settings/Member/ListSection/index.vue, src/repositories/userRepository.js
- [S35A1 - View List Akun Anggota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recIp9I1srTke3d7B?blocks=hide)
- add `getMemberList` method on `userRepository`
- get member data from API
- adjust styling on member table
title: feat get member list data
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @yoslie
=> feat: get member list data

src/components/Settings/Member/ListSection/MemberTable.vue, src/components/Settings/Member/ListSection/index.vue
- [S35A1 - View List Akun Anggota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recIp9I1srTke3d7B?blocks=hide)
- map member status value
title: refactor map member status value
participants: @Ibwedagama @bangunbagustapa @yoslie @naufalihsank
=> refactor: map member status value

src/components/CreateAccount/Form/index.vue
- [S36A1 - Create Account Kontributor](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec9DgwFzFRxyNBjA?blocks=hide)
Title: refactor: change validation flow on create account
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph @doohanas @yoslie
=> refactor: change validation flow on create account

src/components/Settings/Member/ListSection/MemberTable.vue, src/repositories/userRepository.js
Adjust endpoint changes to get a list of members
Title: fix: member list
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph
=> fix: member list

src/components/Settings/Account/RequestUpgradeRoleSection.vue
Title: fix: user information
Participants: @bangunbagustapa @naufalihsank @maulanayuseph @yoslie @Ibwedagama
=> fix: user information

src/components/Settings/Member/ListSection/MemberTable.vue, src/components/Settings/Member/ListSection/MemberTableAction.vue
- Show a modal for table action
Title: chore: show a modal for table action
Participants: @bangunbagustapa @maulanayuseph @yoslie
=> chore: show a modal for table action

src/pages/Settings/MemberDetail.vue, src/repositories/userRepository.js
- [S35A2 - View Detail Akun Anggota](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/reciLujaYRdamR4Ln?blocks=hide)
- add method on `userRepository`
- get member data from API
title: feat member detail
participants: @Ibwedagama @bangunbagustapa @naufalihsank @yoslie
=> feat: member detail

src/common/components/Toast.vue, src/components/Settings/Member/ListSection/MemberTable.vue, src/components/Settings/Member/ListSection/MemberTableAction.vue, src/components/Settings/Member/ListSection/index.vue, src/components/Settings/Member/SetAdminModal.vue, src/pages/Settings/MemberDetail.vue, src/repositories/userRepository.js
- [S35A3 - Set as Admin](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec1A905ivxgX89rf?blocks=hide)
https://user-images.githubusercontent.com/55199533/161672907-1953aa13-cabf-491e-9f34-d206fddd78a4.mov
https://user-images.githubusercontent.com/55199533/161673025-5bc4db03-977b-408e-a977-52376c3713f8.mov
Title: feat: set as admin
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @doohanas @maulanayuseph
=> feat: set as admin

src/components/Settings/Member/ListSection/MemberTable.vue, src/components/Settings/Member/ListSection/MemberTableAction.vue, src/pages/Settings/MemberDetail.vue
Title: fix: member status
Participants: @bangunbagustapa @naufalihsank @maulanayuseph @Ibwedagama
=> fix: member status

src/common/components/Restricted.vue, src/components/NewsInformation/News/NewsTableAction.vue, src/components/Settings/Account/index.vue, src/components/Settings/Member/ListSection/MemberTableAction.vue, src/components/Settings/Member/index.vue, src/main.js, src/pages/Settings/index.vue, src/plugins/permission.js, src/router/routes.js
- limit access to certain routes and functionality based on user's permissions
- [S41A3 - Kontributor](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recifJxpXxqujZywU?blocks=hide)
- [S41A2 - Administrator](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recnggRF6R157aPXc?blocks=hide)
- [S41A1 - Group Admin](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recf5r1jTKYaBFJej?blocks=hide)
- add `$hasPermission` global instance property via Vue Plugin
- refactor `Restricted` component
- add restrictions to some action and functionality
- add restrictions to some route
title: feat role-based access control
participants: @Ibwedagama @naufalihsank @bangunbagustapa @yoslie
=> feat: role based access control

src/components/Settings/Member/ChangeEmailModal.vue, src/components/Settings/Member/ListSection/MemberTableAction.vue, src/pages/Settings/MemberDetail.vue, src/repositories/userRepository.js
- [S35A5 - Ubah Email](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recoGoGjCU2aGLQgJ?blocks=hide)
Change email on member detail
https://user-images.githubusercontent.com/55199533/161709866-d98616d6-b316-4002-9146-55c6bef4fc96.mov
Change email on the table action
https://user-images.githubusercontent.com/55199533/161709908-b0b4fe7e-2467-41aa-a50f-ad4a43cea139.mov
Some validation
https://user-images.githubusercontent.com/55199533/161709923-d3ad4ce1-dc7e-477b-b61e-25927c037837.mov
Title: feat: change email
Participants: @bangunbagustapa @doohanas @Ibwedagama @yoslie @maulanayuseph
=> feat: change email

src/components/Agenda/AgendaTable.vue, src/components/NewsInformation/News/NewsTable.vue, src/components/Settings/Member/ListSection/MemberTable.vue
- fix styling on pagination's page search on `MemberTable`
- fix styling on pagination's page search on `AgendaTable`
- fix styling on pagination's page search on `NewsTable`
**Before**
**After**
title: fix styling on pagination page search
participants: @Ibwedagama @maulanayuseph @maruf12 @bangunbagustapa @yoslie
=> style (pagination): fix styling on pagination page search

src/components/Settings/Member/DeactivateMemberModal.vue, src/components/Settings/Member/ListSection/MemberTableAction.vue, src/pages/Settings/MemberDetail.vue, src/repositories/userRepository.js
- [S35A4 - Make User Deactived](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recz8UnmiMEaceO4U?blocks=hide)
https://user-images.githubusercontent.com/55199533/161920190-587a2c45-6f0a-484c-b5cb-28d1966b2f02.mov
https://user-images.githubusercontent.com/55199533/161920198-27897e05-575a-4a99-a697-72e5b65f6337.mov
Title: feat: deactivate user
Participants: @bangunbagustapa @Ibwedagama @naufalihsank
=> feat: deactivate user

src/components/Settings/Member/SetAdminModal.vue
Fix loading state not show on set admin modal
Title: fix: fix loading state on set admin modal
Participants: @bangunbagustapa @doohanas @Ibwedagama @naufalihsank
=> fix: fix loading state on set admin modal

src/components/Settings/Member/ChangeEmailModal.vue, src/components/Settings/Member/DeactivateMemberModal.vue, src/components/Settings/Member/SetAdminModal.vue
- adjust styling on `ChangeEmailModal`, `DeactivateMemberModal`, `SetAdminModal`
- reset `isError` state on modal close
title: Improve member action modal style
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank
=> Improve: member action modal style

src/components/Settings/Member/DeactivateMemberModal.vue, src/components/Settings/Member/ListSection/MemberTableAction.vue, src/repositories/userRepository.js
- change API endpoint for change member status
- change permission from `user.deactivate` to `user.change-status`
- refactor deactivate member functionality
title: refactor deactivate member functionality
participants: @Ibwedagama @bangunbagustapa @naufalihsank @yoslie
=> refactor: deactivate member functionality

src/components/Login/LoginForm.vue, src/pages/Login.vue
- [T139 - Halaman Login](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recsNjWWAgQmTcmVA?blocks=hide)
Title: fix: fix wording on login page
Participants: @bangunbagustapa @doohanas @naufalihsank @Ibwedagama @yoslie @maulanayuseph @maruf12
=> fix: fix wording on login page

src/common/constants/index.js, src/components/NewsInformation/News/NewsTableAction.vue, src/components/NewsInformation/News/index.vue, src/pages/News/CreateEditNews.vue, src/router/routes.js
- [S29A11 - Enhancement Mircocopy](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/reckUPKrlHy1av6GS?blocks=hide)
Title: improve: microcopy
Participants: @bangunbagustapa @doohanas @yoslie @maulanayuseph @naufalihsank @Ibwedagama
=> improve: microcopy

src/components/CreateAccount/Form/index.vue
Improve nip validation message when creating an account
Title: improve: validation message
Participants: @bangunbagustapa @maulanayuseph @maruf12 @naufalihsank @doohanas @Ibwedagama
=> improve: validation message

src/components/CreateAccount/Form/DetailInformationForm.vue, src/components/CreateAccount/Form/PasswordForm.vue, src/components/CreateAccount/Form/index.vue
title: adjust styling on create-account-form
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie @doohanas
=> style (crate-account-form): adjust styling

src/common/constants/index.js
- [S28A4 - Add Kategori Agenda](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/rec0f1GoQZvnomv7f?blocks=hide)
Title: feat: add a new category to agenda
Participants: @bangunbagustapa @maulanayuseph @naufalihsank @Ibwedagama
=> feat: add a new category to agenda

src/components/Settings/Member/ListSection/MemberTableAction.vue, src/components/Settings/Member/SetAdminModal.vue, src/pages/Settings/MemberDetail.vue
- change `SetAdminModal` props from member name to member email
- adjust props binding on other components using this component
title: refactor set admin modal
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @yoslie @doohanas
=> refactor: set admin modal

src/pages/News/CreateEditNews.vue
[S30A8 - Enhance Set up Author pada Form Create Berita](https://airtable.com/app7SdZInMN1pG6ZL/tblLy5A3qYF19fj1u/viwDUthwzD6mc5jka/recbZuOpaNWCQu7gK?blocks=hide)
Add `author`, `reporter` and `editor` property into the form.
Title: improve: news author
Participants: @bangunbagustapa @Ibwedagama @naufalihsank @yoslie @doohanas
=> improve: news author

src/common/constants/index.js, src/components/NewsInformation/News/index.vue
- change table column from `author` to `created_by`
title: refactor change author column to created by
participants: @Ibwedagama @maulanayuseph @maruf12 @bangunbagustapa @naufalihsank @yoslie
=> refactor: change author column to created by

src/components/NewsInformation/News/NewsPreview.vue
- adjust `author` computed property
- add `editor`and `reporter` computed property
- add editor and reporter information to the template
title: improve add reporter and editor information
participants: @Ibwedagama @maruf12 @bangunbagustapa @doohanas
=> improve: add reporter and editor information

src/components/Login/LoginForm.vue
Add error message for an inactive account
Title: fix: fix error message for login
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph @yoslie
=> fix: fix error message for login

src/pages/News/CreateEditNews.vue, src/pages/News/NewsPreview.vue
https://user-images.githubusercontent.com/55199533/163154764-64f662ca-b245-4546-8cf5-e6339131e7fc.mov
Title: fix: display error modal for unauthorized resource
Participants: @bangunbagustapa @maulanayuseph @Ibwedagama @yoslie @doohanas
=> fix: display error modal for unauthorized resource

src/components/NewsInformation/News/index.vue
title: refactor add default count value
participants: @Ibwedagama @maulanayuseph @bangunbagustapa @naufalihsank @yoslie
=> refactor: add default count value

src/common/components/Header.vue
- [T138 - Pengaturan Akun  - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recBuv2Bp19MQkmXX?blocks=hide)
Close the user dropdown when clicking outside the area 
- Add clickaway directive
Title: fix: user dropdown
Participants: @bangunbagustapa @Ibwedagama @maulanayuseph @maruf12 @naufalihsank @yoslie
=> fix: user dropdown

src/components/NewsInformation/News/NewsPreview.vue
- fix: image not showing properly on mode local
title: fix news preview image
participants: @Ibwedagama @bangunbagustapa @yoslie
=> fix: news preview image

src/components/NewsInformation/News/NewsPreview.vue, src/pages/News/CreateEditNews.vue
- Fix data binding on news preview
Title: fix: fix data binding on news preview
Participants: @bangunbagustapa @Ibwedagama @yoslie
=> fix: fix data binding on news preview

src/components/NewsInformation/News/NewsPreview.vue, src/pages/News/NewsPreview.vue
- refactor (news-preview): add loading state to news-preview page
- refactor (news-preview): render skeleton using loading props
- refactor (news-preview): add editor property to news default value
title: refactor news preview skeleton
=> refactor: news preview skeleton

src/components/Settings/Member/ListSection/MemberTable.vue
title: refactor member status title information
=> refactor: member status title information

src/common/components/Header.vue, src/pages/Agenda/CreateEditAgenda.vue
- refactor (header): remove notification number
- refactor (edit-agenda): add alert modal if user is unauthorized
title: add alert modal if user is unauthorized
=> refactor: add alert modal if user is unauthorized

src/pages/News/CreateEditNews.vue
https://user-images.githubusercontent.com/55199533/163530009-235f00ba-d354-4f68-a3b1-b2de9580450e.mov
Title: fix: fix tags not watched when updating the news
=> fix: fix tags not watched when updating the news

src/App.vue, src/common/components/ForbiddenAccessModal.vue, src/common/helpers/event-bus.js, src/layouts/AppLayoutPrivate.vue, src/pages/Agenda/AgendaDetail.vue, src/pages/Agenda/CreateEditAgenda.vue, src/pages/News/CreateEditNews.vue, src/pages/News/NewsPreview.vue, src/pages/Settings/MemberDetail.vue
add global authorization alert
- feat (event-bus): add event-bus helper
- feat: add forbidden-access-modal component
- refactor (app-layout-private): add forbidden-access-modal component
- refactor (create-edit-news): remove unused modal; add event bus on http response 403
- refactor (create-edit-agenda): remove unused modal; add event bus on http response 403
- refactor (agenda-detail): remove unused modal; add event bus on http response 403
- refactor (news-preview): remove unused modal; add event bus on http response 403
title: feat global authorization alert
=> feat: global authorization alert

src/pages/News/CreateEditNews.vue
- fix (news-preview): fix prefix not change on news-preview
=> fix: prefix not change on news-preview

src/common/components/Header.vue, src/common/constants/index.js, src/components/Login/LoginForm.vue, src/components/Settings/Account/index.vue
Temporarily hide features that have not been fully implemented
- refactor (login): temporarily hide forgot password button
- refactor (header): temporarily hide notification button
- refactor (settings): temporarily hide notification section
- refactor (constant): temporarily remove sortable property on MEMBER_T…
title: refactor temporary hide items
participants: @Ibwedagama @bangunbagustapa @yoslie
=> refactor: temporary hide items

src/store/modules/auth.js
Get access token and refresh token only from cookies
Title: fix(auth): fix access token and refresh token from cookies
Participants: @bangunbagustapa @Ibwedagama @maruf12 @maulanayuseph @agunghide
=> hotfix(auth): fix access token and refresh token from cookies

src/store/modules/auth.js
- Fix invalid token specified [#206](https://github.com/jabardigitalservice/portal-jabar-cms/pull/206)
Title: Release version 1.0.1
Participants: @bangunbagustapa @yoslie @agunghide @maulanayuseph @Ibwedagama
=> Release version 1.0.1

src/components/CreateAccount/Form/DetailInformationForm.vue, src/components/Settings/Account/PersonalInformationSection.vue
- [T178 - CMS - Buat Akun Kontributor - Improvement validasi jabatan](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recKkVL4RiegJMtbE?blocks=hide)
- [T177 - CMS - Informasi Personal - Improvement validasi jabatan](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recu9xTxVZr4SiH2D?blocks=hide)
Title: refactor: occupation validation
Participants: @bangunbagustapa @maruf12 @Ibwedagama @agunghide @yoslie
=> refactor: occupation validation

src/components/CreateAccount/Form/DetailInformationForm.vue, src/components/Settings/Account/PersonalInformationSection.vue
- Occupation validation rules [#208](https://github.com/jabardigitalservice/portal-jabar-cms/pull/208)
Title: Release version 1.0.2
Participants: @bangunbagustapa @doohanas @maulanayuseph @Ibwedagama
=> Release version 1.0.2

src/components/Agenda/AgendaPreview.vue
title: fix agenda preview date bug
participants: @Ibwedagama @agunghide @bangunbagustapa @doohanas
=> fix (agenda-preview): fix agenda preview not showing the correct date

src/components/Agenda/AgendaPreview.vue
- Fix date on agenda preview [#210](https://github.com/jabardigitalservice/portal-jabar-cms/pull/210)
Title: Release version 1.0.3
=> Release version 1.0.3

src/pages/News/CreateEditNews.vue
- [T194 - Default waktu penayangan berita ketika ubah berita - FE](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/recvZJO899HguaZPt?blocks=hide)
- fix (edit-news): fix date-time bug on edit news
=> fix (edit-news): fix date-time bug on edit news

src/pages/Agenda/CreateEditAgenda.vue
- [T197 - Mengubah agenda yang sedang berlangsung - FE
](https://airtable.com/app7SdZInMN1pG6ZL/tblB9pTkT5LrZHnIp/viwQAZLJD0D9EGBbX/rec2JwrsuKl5jpBP2?blocks=hide)
- fix (agenda): fix changing time on ongoing event
=> fix (agenda): fix changing time on ongoing event

src/components/Agenda/AgendaPreview.vue, src/pages/Agenda/CreateEditAgenda.vue, src/pages/News/CreateEditNews.vue
- fix (agenda): fix changing time on ongoing event
- fix (edit-news): fix date-time bug on edit news
- fix (agenda-preview): fix agenda preview not showing the correct date
title: Release production v1.0.4
participants: @Ibwedagama @agunghide @doohanas
=> Release Production v1.0.4

src/pages/Agenda/CreateEditAgenda.vue
- [S28A6 - Take out validasi disable back date](https://app.clickup.com/t/2xwwb5n)
title: enable backdate
participants: @naufalihsank @Ibwedagama @agunghide
=> feat (agenda-form): enable backdate

src/pages/Agenda/CreateEditAgenda.vue
- Enable Agenda backdate
title: Release Production v1.0.5
participants: @Ibwedagama @naufalihsank @adzharamrullah
=> Release Production v1.0.5

src/common/components/Header.vue, src/common/components/Sidebar.vue, src/common/helpers/vee-validate.js, src/components/Login/ForgotPassword.vue, src/components/Login/LoginForm.vue, src/components/Services/MasterData/Form/StepOne.vue, src/components/Services/MasterData/index.vue, src/pages/Login.vue, src/pages/Services/MasterDataServiceDetail.vue, src/store/modules/public-service/masterDataForm.js
[fix bugs on production](https://app.clickup.com/t/860qq69bh)
- Fitur: Master Data Layanan
T290 - Issue tampilan popup konfirmasi delete
T291 - Posisi snackbar tarif layanan
T292 - Validasi jam operasional
T294 - Issue validasi tarif layanan
T295 - Issue validasi link
title: hotfix production issue tickets
participants: @Ibwedagama @doohanas @rachadiannovansyah @rizfirman
=> hotfix: production issue tickets

src/common/components/Sidebar.vue, src/common/constants/index.js, src/router/routes.js
* feat: add permission to landing-page menu
* feat: add permission to access landing-page route
title: release portal jabar cms v1.3.0
participants: @Ibwedagama @maulanayuseph @rizfirman @sheilaazhara @naufalihsank @rayfajars @yoslie @doohanas
=> Release Portal Jabar CMS v1.3.0

src/components/Services/MasterData/index.vue, src/components/Services/Publication/Form/StepOne.vue
[S56A9 - Add Kategori Layanan Jabarprov](https://app.clickup.com/t/860r47bjc)
[T300 - Reset page list master data layanan di tab berbeda](https://app.clickup.com/t/860qvn5r6)
title: release portal jabar cms v1.5.2
participants: @Ibwedagama @yoslie @doohanas
=> Release Portal Jabar CMS v1.5.2

src/pages/LandingPage/CreateEditInfographicsBanner.vue
- disable validation dirty
- update default isActiveLink
- update validation link in form create infographics banner
title: disable validation dirty, update default isActiveLink, update validation link in form create infographics banner
participants: @yoslie @naufalihsank
=> update: disable validation dirty, update default isActiveLink, update validation link in form create infographics banner

src/pages/LandingPage/InfoGraphicsDetailPage.vue
- update action button edit route link
- update delete function
- update wording popup confirmation delete
title:  fix action link edit and delete banner, update function delete in page detail infographics banner
participants: @yoslie @doohanas @naufalihsank @maulanayuseph @Ibwedagama
=> update: fix action link edit and delete banner, update function delete

src/components/LandingPage/InfoGraphics/InfoGraphicsBannerTableAction.vue, src/components/LandingPage/InfoGraphics/index.vue, src/components/LandingPage/PopupBanner/PopupBannerTableAction.vue, src/components/LandingPage/PopupBanner/index.vue, src/pages/LandingPage/InfoGraphicsDetailPage.vue, src/pages/LandingPage/PopupBannerDetailPage.vue, src/pages/LandingPage/index.vue, src/router/routes.js
refactor landing page menu tab functionality using link tabbar component 
- change component tab into link tabbar
- update route path
title: refactor landing page menu tab functionality using link tabbar component 
participants: @yoslie @naufalihsank @Ibwedagama @sheilaazhara @doohanas @maulanayuseph
=> update: refactor tab component using link tabbar and update route link

src/components/LandingPage/InfoGraphics/InfoGraphicsBannerTable.vue, src/components/LandingPage/InfoGraphics/index.vue
title: fix infinite scroll container height
participants: @naufalihsank @yoslie
=> fix (infographics): fix infinite scroll container height

src/router/routes.js
[change header menu route name all page landing page menu](https://github.com/jabardigitalservice/portal-jabar-cms/commit/8826cd002df3c411997b664b9dc0ea325a560f81)
title: change header menu route name all page landing page menu
participants: @yoslie @naufalihsank @marsellavaleria19 @doohanas
=> update: change header menu route name all page landing page menu

src/components/LandingPage/InfoGraphics/InfoGraphicsBannerTable.vue, src/components/LandingPage/InfoGraphics/index.vue
title: fix non active state while edit sorting mode
participants: @naufalihsank @yoslie @Ibwedagama @doohanas
=> fix (infographics): fix non active state while edit sorting mode

src/pages/LandingPage/CreateEditAccessLink.vue, src/router/routes.js
update edit route and function edit data quick link
title: update edit route and function edit data quick link
participants: @yoslie @doohanas
=> feat: update edit route and function edit data quick link

src/pages/LandingPage/CreateEditAccessLink.vue
fix validation title max length character
title: fix validation title max length character in form add quick link
participants: @yoslie @naufalihsank @doohanas
=> update: fix validation title length

src/pages/LandingPage/CreateEditAccessLink.vue
title: reset query params on select icon in list icon quick link
participants: @yoslie @doohanas @Ibwedagama @agunghide @naufalihsank
=> improvement: reset query params on select icon in list icon quick link

src/pages/ArchiveAndDocument/CreateEditArchiveAndDocument.vue
[create function store draft and publish data archive document](https://github.com/jabardigitalservice/portal-jabar-cms/commit/3cea02fac118b153a7324760c60e4cfaaa9d876a)
title: create function store draft and publish data archive document
participants: @yoslie @agunghide @Ibwedagama @naufalihsank
=> update: create function store draft and publish data archive document

src/common/helpers/download.js, src/components/Profiles/Documents/DocumentsDetailTable.vue, src/components/Profiles/Documents/index.vue, src/pages/Profiles/DocumentDetail.vue
- [fix (documents): fix microcopy and reset page when filtering](https://github.com/jabardigitalservice/portal-jabar-cms/commit/7855eeaf09af10ae28d08bb14049dd91c823952a)
- [feat (documents): direct document download](https://github.com/jabardigitalservice/portal-jabar-cms/commit/38c2155a74a6dd5c1a79cd03479ab65d76300187)
title: fix microcopy, reset page when filtering, and direct download
participants: @naufalihsank @Ibwedagama @yoslie @sheilaazhara
=> fix (documents): fix microcopy, reset page when filtering, and direct download

src/components/Profiles/Documents/DocumentsTableAction.vue, src/components/Profiles/Documents/index.vue
refactor popup message to create custom message for recover document
title: refactor popup message to create custom message for recover document
participants: @yoslie @Ibwedagama @doohanas @naufalihsank
=> update: refactor popup message to create custom message for recover document

src/pages/Profiles/CreateEditArchiveAndDocument.vue
fix validation button draft and publish document on edit document
title: fix validation button draft and publish document on edit document
participants: @yoslie @sheilaazhara @agunghide @rizfirman @doohanas
=> update: fix validation button draft and publish document on edit document

src/pages/Profiles/CreateEditArchiveAndDocument.vue
title: Release portal jabar cms v1.7.1 - hotfix clear state document type on delete document
participants: @yoslie
=> Release portal jabar cms v1.7.1

src/components/Profiles/Documents/DocumentsDetailTable.vue, src/components/Profiles/Documents/index.vue, src/pages/Profiles/CreateEditArchiveAndDocument.vue
[Improvement Code Quality berdasarkan metric Sonarqube](https://app.clickup.com/t/860rpzbt4)
- [add id attribute to th element](https://github.com/jabardigitalservice/portal-jabar-cms/commit/5623d0b7f02f094e30a3288f205546dbe21172aa)
- [simplify code to immediately return expression](https://github.com/jabardigitalservice/portal-jabar-cms/commit/780fa91c6652643a2cb7cf6769706497309f761c)
- [update function to reduce its Cognitive Complexity](https://github.com/jabardigitalservice/portal-jabar-cms/commit/c0ac8d41a18969ab9ebf57354dce109bf109eb37)
title: improve code reliability and code smells based on sonarqube feedback
participants: @yoslie @Ibwedagama @marsellavaleria19
=> Improvement code quality in module archive and documents

src/components/Profiles/Documents/DocumentsDetailTable.vue, src/components/Profiles/Documents/index.vue, src/pages/Profiles/CreateEditArchiveAndDocument.vue
title: Release portal jabar cms v1.7.2 - update upload document params, improve code quality
participants: @yoslie @naufalihsank @rayfajars
=> Release portal jabar cms v1.7.2

src/pages/Maintenance/index.vue, src/router/index.js, src/router/routes.js
There is a security improvement currently ongoing that causes API not to work properly. The action plan is to add maintenance for Portal Jabar CMS temporarily
- add a global maintenance page
- add maintenance logic on the `router.js`
title: hotfix add maintenance page
participants: @Ibwedagama @maulanayuseph @rayfajars
=> hotfix (maintenance): redirect all page to maintenance page
